version: '3.'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.1
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    network_mode: host

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


